# Generated by Django 4.2.6 on 2024-02-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_store', '__first__'),
        ('cart', '0002_cart_session_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardItem',
            new_name='CartItem',
        ),
    ]
